site_name: Python Testing Guide

theme:
  name: "material"
  palette:
    scheme: slate

nav:
  - Tutorial: tutorial.md
  - Guide: guide.md

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tilde
